package BloodBank;


/**
* BloodBank/BloodBankServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BloodBankServer.idl
* Friday, August 2, 2024 11:25:27 PM MMT
*/

abstract public class BloodBankServerHelper
{
  private static String  _id = "IDL:BloodBank/BloodBankServer:1.0";

  public static void insert (org.omg.CORBA.Any a, BloodBank.BloodBankServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BloodBank.BloodBankServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BloodBank.BloodBankServerHelper.id (), "BloodBankServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BloodBank.BloodBankServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BloodBankServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BloodBank.BloodBankServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BloodBank.BloodBankServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BloodBank.BloodBankServer)
      return (BloodBank.BloodBankServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BloodBank._BloodBankServerStub stub = new BloodBank._BloodBankServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BloodBank.BloodBankServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BloodBank.BloodBankServer)
      return (BloodBank.BloodBankServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BloodBank._BloodBankServerStub stub = new BloodBank._BloodBankServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
