package BloodBank;


/**
* BloodBank/BloodBankServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BloodBankServer.idl
* Friday, August 2, 2024 11:25:27 PM MMT
*/

public interface BloodBankServerOperations 
{
  String[] bloodsearch (String bloodtype);
  String[] nrc_check (String donor_nrc);
  String[] getInventory ();
  String[] getInventoryHistory ();
  String getDonationHistory (String donor_nrc);
  String bloodrequest (String blood_id, String receiver_name, String receiver_phone, String receive_date, String receiver_age, String receiver_gender, String receiver_address, String receiver_email);
  String blooddonate (String bloodtype, String donor_name, String donor_phone, String donation_date, String donor_age, String donor_gender, String donor_address, String donor_email, String donor_nrc);
} // interface BloodBankServerOperations
