package BloodBank;

/**
* BloodBank/BloodBankServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BloodBankServer.idl
* Friday, August 2, 2024 11:25:27 PM MMT
*/

public final class BloodBankServerHolder implements org.omg.CORBA.portable.Streamable
{
  public BloodBank.BloodBankServer value = null;

  public BloodBankServerHolder ()
  {
  }

  public BloodBankServerHolder (BloodBank.BloodBankServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BloodBank.BloodBankServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BloodBank.BloodBankServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BloodBank.BloodBankServerHelper.type ();
  }

}
